### PR TITLE
chore: Add GitHub Action for CSS linting

### PR DESCRIPTION
**Pull request by nschonni**
- Add a GH Action to run if the CSS is touched
- Add missing Stylelint config
- Fix globbing pattern for stylelint

### CODE REVIEW

**Comment by nschonni** [comment]
@delisma I'm assuming from the pushes you're switching back to gh-pages. These failures were already there, but will only fail when someone touches the CSS files or package files and don't fix it

**Comment by delisma** [comment]
So what are the expectations of that linter? It seems like that `alpha.gc-design-system-nav.css` need to be addressed, before we merged. Will we have the same issues with other css files? Should we move them to `scss` files instead?

**Review by delisma — COMMENTED** [review]
@nschonni Should we include the `package-lock.json` file in the PR?

**Comment by nschonni** [comment]
@delisma for a website, I think it makes sense. It ensures that you can use `npm ci` to get consistent results locally and in the CI

**Review by delisma — APPROVED** [review]

**Pull request merged**
