### PR TITLE
Cleanup more validator errors

### PR DESCRIPTION
**Pull request by nschonni**
Note: for the checking to be effective, you might need to change your flow to start using Pull Requests instead of pushing directly to the master branch. There are currently a few new issues around empty images since the first PR

### CODE REVIEW

**Review by jmealing — APPROVED** [review]

**Comment by jmealing** [comment]
Hey - thanks! I've changed what made sense manually. 

Some could not be implemented - especially those on the long doc pattern, because we're still working on the script. For example, changing the headers right now would cause targeting issues, also the </a> tag is not a stray - it has an link. The goal in this space is for us to get something working to demonstrate a concept - most of us tinkering are non-devs, and we prioritize cleanup after we get the look and behaviour we want. Since we weren't expecting any PRs we've all been working on the master branch, but will look at improving our process to work better with contributors. In this space some designs are intentional for experimentation, like the time element form "July 13, 2019".

The most value would be in correcting errors in the real repos - EN: https://github.com/canada-ca/design-system and FR: https://github.com/canada-ca/systeme-conception

**Comment by jmealing** [comment]
To help clean up this space and better facilitate PRs for the development of the design-patterns, we're going to move our "in progress" content, like the long doc, out of this repo.

**Comment by nschonni** [comment]
> like the time element form "July 13, 2019

That isn't valid HTML, which is why it get's flagged ;)
You'll figure out your process, this was just to flag stuff early, since it probably doesn't make sense to test designs that aren't valid HTML. Those wouldn't be patterns that could end up in design guides.

**Comment by jmealing** [comment]
People do understand the date clearer and easier in the "readable" July 13, 2019 format. Surely there's a way to write that in a valid way?

For example: Would it be valid HTML to have the correct date format present in the time property tag, but set to wb-inv. Then, we have it so people SEE the visual is of "July 13, 2019" as <p> or another tag.

**Comment by nschonni** [comment]
Looks like you're OK setting the text to the other format, as long as you fill in the ISO format in the datetime attribute https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time

**Comment by jmealing** [comment]
Ah that’s great, thank you - we’re definitely trying to incorporate as much of the correct way of doing things from the very start when we know how. 

I really appreciate you taking the time to point these issues out. I’ve added this to my notes to fix across projects.

**Pull request closed without merging**
