### PR TITLE
Travis setup

### PR DESCRIPTION
**Pull request by nschonni**
Initial setup of CI and fixing of HTML validation issues.
There is still an issue with the branding that should be switched to an `img` tag like upstream https://github.com/wet-boew/wet-boew/blob/master/site/includes/brand.hbs

### CODE REVIEW

**Comment by nschonni** [comment]
I rebased without fixing any of the new issues to show an example of what this catches

**Comment by nschonni** [comment]
@quidampepin if your group is going to start using PRs, I can rebase this again

**Comment by quidampepin** [comment]
@nschonni We are still trying to set up the repos properly, and to come up with a process for departments to contribute to the design system (more specifically: improving existing patterns/templates or suggesting new ones). When the Canada.ca visual update launches (in the next few weeks), we will also launch an updated Canada.ca design system. This update basically sets the stage for collaborative work on future updates.  

In a nutshell, the "official" templates/patterns, the ones that are fully approved, validated, coded, etc., will reside on https://github.com/canada-ca/design-system and https://github.com/canada-ca/systeme-conception, while this repo (https://github.com/canada-ca/design-system-systeme-conception/) will be used an experimental environment for people to suggest improvements or new patterns/templates. When we are ready, the process will be posted in this repo. 

I hope this is clear - I'm not at all a GitHub expert (nor am I a developer...).

**Comment by patlaj** [comment]
Hey @nschonni  -  this sets up automatic travis checks? Like @quidampepin says, this would be very useful on:
https://github.com/canada-ca/design-system and https://github.com/canada-ca/systeme-conception

It'd be useful here too since though so we can get contributions here - could you rebase and resubmit and one of us will accept it. Thanks!

**Comment by nschonni** [comment]
Rebased, but I think I have to go over everything again since there are new issues and deleted/new files

**Comment by nschonni** [comment]
OK, this should be landable now. There are more things to fix up that are still suppressed, but I don't want to hit a bad rebase again if you make more changes before this lands

**Pull request merged**
